/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AbrirChamadoRouteImport } from './routes/abrir-chamado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedChamadosRouteImport } from './routes/_authenticated/chamados'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosAutomacaoComercialRouteImport } from './routes/servicos.automacao-comercial'
import { Route as ServicosConsultoriaRouteImport } from './routes/servicos.consultoria'
import { Route as ServicosSuporteRemotoRouteImport } from './routes/servicos.suporte-remoto'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminSegurancaRouteImport } from './routes/_authenticated/admin.seguranca'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedChamadosTicketIdRouteImport } from './routes/_authenticated/chamados.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirChamadoRoute = AbrirChamadoRouteImport.update({
  id: '/abrir-chamado',
  path: '/abrir-chamado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChamadosRoute = AuthenticatedChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosAutomacaoComercialRoute =
  ServicosAutomacaoComercialRouteImport.update({
    id: '/automacao-comercial',
    path: '/automacao-comercial',
    getParentRoute: () => ServicosRoute,
  } as any)
const ServicosConsultoriaRoute = ServicosConsultoriaRouteImport.update({
  id: '/consultoria',
  path: '/consultoria',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosSuporteRemotoRoute = ServicosSuporteRemotoRouteImport.update({
  id: '/suporte-remoto',
  path: '/suporte-remoto',
  getParentRoute: () => ServicosRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/admin/auditoria',
    path: '/admin/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSegurancaRoute =
  AuthenticatedAdminSegurancaRouteImport.update({
    id: '/admin/seguranca',
    path: '/admin/seguranca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChamadosTicketIdRoute =
  AuthenticatedChamadosTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedChamadosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir-chamado': typeof AbrirChamadoRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/portal': typeof PortalRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/chamados': typeof AuthenticatedChamadosRouteWithChildren
  '/painel': typeof AuthenticatedPainelRoute
  '/servicos/automacao-comercial': typeof ServicosAutomacaoComercialRoute
  '/servicos/consultoria': typeof ServicosConsultoriaRoute
  '/servicos/suporte-remoto': typeof ServicosSuporteRemotoRoute
  '/servicos/': typeof ServicosIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/seguranca': typeof AuthenticatedAdminSegurancaRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/chamados/$ticketId': typeof AuthenticatedChamadosTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir-chamado': typeof AbrirChamadoRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/portal': typeof PortalRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/chamados': typeof AuthenticatedChamadosRouteWithChildren
  '/painel': typeof AuthenticatedPainelRoute
  '/servicos/automacao-comercial': typeof ServicosAutomacaoComercialRoute
  '/servicos/consultoria': typeof ServicosConsultoriaRoute
  '/servicos/suporte-remoto': typeof ServicosSuporteRemotoRoute
  '/servicos': typeof ServicosIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/seguranca': typeof AuthenticatedAdminSegurancaRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/chamados/$ticketId': typeof AuthenticatedChamadosTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/abrir-chamado': typeof AbrirChamadoRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/portal': typeof PortalRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/chamados': typeof AuthenticatedChamadosRouteWithChildren
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/servicos/automacao-comercial': typeof ServicosAutomacaoComercialRoute
  '/servicos/consultoria': typeof ServicosConsultoriaRoute
  '/servicos/suporte-remoto': typeof ServicosSuporteRemotoRoute
  '/servicos/': typeof ServicosIndexRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/seguranca': typeof AuthenticatedAdminSegurancaRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/chamados/$ticketId': typeof AuthenticatedChamadosTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir-chamado'
    | '/auth'
    | '/contato'
    | '/faq'
    | '/portal'
    | '/privacidade'
    | '/servicos'
    | '/sobre'
    | '/termos'
    | '/chamados'
    | '/painel'
    | '/servicos/automacao-comercial'
    | '/servicos/consultoria'
    | '/servicos/suporte-remoto'
    | '/servicos/'
    | '/admin/auditoria'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/chamados/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir-chamado'
    | '/auth'
    | '/contato'
    | '/faq'
    | '/portal'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/chamados'
    | '/painel'
    | '/servicos/automacao-comercial'
    | '/servicos/consultoria'
    | '/servicos/suporte-remoto'
    | '/servicos'
    | '/admin/auditoria'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/chamados/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/abrir-chamado'
    | '/auth'
    | '/contato'
    | '/faq'
    | '/portal'
    | '/privacidade'
    | '/servicos'
    | '/sobre'
    | '/termos'
    | '/_authenticated/chamados'
    | '/_authenticated/painel'
    | '/servicos/automacao-comercial'
    | '/servicos/consultoria'
    | '/servicos/suporte-remoto'
    | '/servicos/'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/seguranca'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/chamados/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AbrirChamadoRoute: typeof AbrirChamadoRoute
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  PortalRoute: typeof PortalRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir-chamado': {
      id: '/abrir-chamado'
      path: '/abrir-chamado'
      fullPath: '/abrir-chamado'
      preLoaderRoute: typeof AbrirChamadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chamados': {
      id: '/_authenticated/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof AuthenticatedChamadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/automacao-comercial': {
      id: '/servicos/automacao-comercial'
      path: '/automacao-comercial'
      fullPath: '/servicos/automacao-comercial'
      preLoaderRoute: typeof ServicosAutomacaoComercialRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/consultoria': {
      id: '/servicos/consultoria'
      path: '/consultoria'
      fullPath: '/servicos/consultoria'
      preLoaderRoute: typeof ServicosConsultoriaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/suporte-remoto': {
      id: '/servicos/suporte-remoto'
      path: '/suporte-remoto'
      fullPath: '/servicos/suporte-remoto'
      preLoaderRoute: typeof ServicosSuporteRemotoRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/seguranca': {
      id: '/_authenticated/admin/seguranca'
      path: '/admin/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AuthenticatedAdminSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados/$ticketId': {
      id: '/_authenticated/chamados/$ticketId'
      path: '/$ticketId'
      fullPath: '/chamados/$ticketId'
      preLoaderRoute: typeof AuthenticatedChamadosTicketIdRouteImport
      parentRoute: typeof AuthenticatedChamadosRoute
    }
  }
}

interface AuthenticatedChamadosRouteChildren {
  AuthenticatedChamadosTicketIdRoute: typeof AuthenticatedChamadosTicketIdRoute
}

const AuthenticatedChamadosRouteChildren: AuthenticatedChamadosRouteChildren = {
  AuthenticatedChamadosTicketIdRoute: AuthenticatedChamadosTicketIdRoute,
}

const AuthenticatedChamadosRouteWithChildren =
  AuthenticatedChamadosRoute._addFileChildren(
    AuthenticatedChamadosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChamadosRoute: typeof AuthenticatedChamadosRouteWithChildren
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminSegurancaRoute: typeof AuthenticatedAdminSegurancaRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChamadosRoute: AuthenticatedChamadosRouteWithChildren,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminSegurancaRoute: AuthenticatedAdminSegurancaRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServicosRouteChildren {
  ServicosAutomacaoComercialRoute: typeof ServicosAutomacaoComercialRoute
  ServicosConsultoriaRoute: typeof ServicosConsultoriaRoute
  ServicosSuporteRemotoRoute: typeof ServicosSuporteRemotoRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosAutomacaoComercialRoute: ServicosAutomacaoComercialRoute,
  ServicosConsultoriaRoute: ServicosConsultoriaRoute,
  ServicosSuporteRemotoRoute: ServicosSuporteRemotoRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AbrirChamadoRoute: AbrirChamadoRoute,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  PortalRoute: PortalRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
